format = """
$directory\
$git_branch\
$git_status\
$kubernetes\
$aws\
$python\
$nodejs\
$terraform\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[kubernetes]
disabled = false
format = "[$symbol$context( \\($namespace\\))]($style) "
symbol = "☸ "
detect_files = ["k8s", "kubernetes"]

[aws]
disabled = false
format = "[$symbol($profile )(\\($region\\))]($style) "
symbol = "☁️ "

[python]
format = "[$symbol$version]($style) "
symbol = " "

[nodejs]
format = "[$symbol$version]($style) "
symbol = " "
detect_files = ["package.json", ".node-version"]

[terraform]
format = "[$symbol$version]($style) "
symbol = "💠 "

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
